services:
  # Backend API Service
  - type: web
    name: cookvault-backend
    runtime: docker
    plan: starter
    dockerfilePath: ./backend/Dockerfile.render
    region: oregon
    branch: main
    healthCheckPath: /api/health
    envVars:
      - key: FLASK_ENV
        value: production
      - key: PORT
        value: "8000"
      - key: GUNICORN_WORKERS
        value: "2"
      - key: LOG_LEVEL
        value: info
      - key: UPLOAD_FOLDER
        value: uploads
      - key: MAX_CONTENT_LENGTH
        value: "16777216"
      - key: RATELIMIT_DEFAULT
        value: 60/hour
      - key: SESSION_COOKIE_SECURE
        value: "true"
      # These need to be set in Render dashboard as secrets
      - key: SECRET_KEY
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: REDIS_URL
        sync: false
      - key: ANTHROPIC_API_KEY
        sync: false
      - key: GOOGLE_BOOKS_API_KEY
        sync: false
      - key: CORS_ORIGINS
        sync: false

  # Frontend Static Site  
  - type: web
    name: cookvault-frontend
    runtime: static
    buildCommand: cd frontend && npm ci && npm run build
    staticPublishPath: ./frontend/dist
    pullRequestPreviewsEnabled: true
    branch: main
    buildFilter:
      paths:
        - frontend/**
    headers:
      - path: /*
        name: X-Frame-Options
        value: DENY
      - path: /*
        name: X-Content-Type-Options
        value: nosniff
      - path: /*
        name: Referrer-Policy
        value: strict-origin-when-cross-origin
      - path: /*
        name: Permissions-Policy
        value: camera=(), microphone=(), geolocation=()
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: VITE_API_URL
        fromService:
          type: web
          name: cookvault-backend
          property: host