version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: cookbook_db
      POSTGRES_USER: cookbook_user
      POSTGRES_PASSWORD: cookbook_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U cookbook_user -d cookbook_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data

  backend:
    build: .
    ports:
      - "5000:5000"
    environment:
      FLASK_ENV: development
      DATABASE_URL: postgresql://cookbook_user:cookbook_pass@postgres:5432/cookbook_db
      REDIS_URL: redis://redis:6379/0
    volumes:
      - .:/app
      - uploads_volume:/app/uploads
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
    command: flask run --host=0.0.0.0 --debug

volumes:
  postgres_data:
  redis_data:
  uploads_volume: