"""Add account deletion fields to user model

Revision ID: 22db193b35d3
Revises: c1d2e3f4g5h6
Create Date: 2026-01-31 15:24:08.855257

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "22db193b35d3"
down_revision = "c1d2e3f4g5h6"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Only drop the temp table if it exists (cleanup from interrupted migration)
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    if "_alembic_tmp_recipe" in inspector.get_table_names():
        op.drop_table("_alembic_tmp_recipe")
    with op.batch_alter_table("processing_job", schema=None) as batch_op:
        batch_op.drop_column("page_number")

    with op.batch_alter_table("recipe", schema=None) as batch_op:
        batch_op.drop_column("page_number")

    with op.batch_alter_table("recipe_image", schema=None) as batch_op:
        batch_op.drop_column("page_number")

    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.add_column(sa.Column("deleted_at", sa.DateTime(), nullable=True))
        batch_op.add_column(
            sa.Column("deletion_scheduled_for", sa.DateTime(), nullable=True)
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.drop_column("deletion_scheduled_for")
        batch_op.drop_column("deleted_at")

    with op.batch_alter_table("recipe_image", schema=None) as batch_op:
        batch_op.add_column(sa.Column("page_number", sa.INTEGER(), nullable=True))

    with op.batch_alter_table("recipe", schema=None) as batch_op:
        batch_op.add_column(sa.Column("page_number", sa.INTEGER(), nullable=True))

    with op.batch_alter_table("processing_job", schema=None) as batch_op:
        batch_op.add_column(sa.Column("page_number", sa.INTEGER(), nullable=True))

    op.create_table(
        "_alembic_tmp_recipe",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("title", sa.VARCHAR(length=200), nullable=False),
        sa.Column("description", sa.TEXT(), nullable=True),
        sa.Column("cookbook_id", sa.INTEGER(), nullable=True),
        sa.Column("page_number", sa.INTEGER(), nullable=True),
        sa.Column("prep_time", sa.INTEGER(), nullable=True),
        sa.Column("cook_time", sa.INTEGER(), nullable=True),
        sa.Column("servings", sa.INTEGER(), nullable=True),
        sa.Column("difficulty", sa.VARCHAR(length=50), nullable=True),
        sa.Column("source", sa.VARCHAR(length=200), nullable=True),
        sa.Column("created_at", sa.DATETIME(), nullable=False),
        sa.Column("updated_at", sa.DATETIME(), nullable=False),
        sa.Column("is_public", sa.BOOLEAN(), nullable=False),
        sa.Column("published_at", sa.DATETIME(), nullable=True),
        sa.Column("is_featured", sa.BOOLEAN(), nullable=False),
        sa.Column("featured_at", sa.DATETIME(), nullable=True),
        sa.Column("user_id", sa.INTEGER(), nullable=True),
        sa.Column("uploaded_by_id", sa.INTEGER(), nullable=True),
        sa.ForeignKeyConstraint(
            ["cookbook_id"],
            ["cookbook.id"],
        ),
        sa.ForeignKeyConstraint(
            ["uploaded_by_id"], ["user.id"], name=op.f("fk_recipe_uploaded_by_id")
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###
