"""Add skip_cache to processing jobs

Revision ID: 31bb03084408
Revises: f43930b98012
Create Date: 2025-12-26 15:19:45.396293

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31bb03084408'
down_revision = 'f43930b98012'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('multi_recipe_job', schema=None) as batch_op:
        batch_op.add_column(sa.Column('skip_cache', sa.Boolean(), nullable=False, server_default='0'))

    with op.batch_alter_table('processing_job', schema=None) as batch_op:
        batch_op.add_column(sa.Column('skip_cache', sa.Boolean(), nullable=False, server_default='0'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('processing_job', schema=None) as batch_op:
        batch_op.drop_column('skip_cache')

    with op.batch_alter_table('multi_recipe_job', schema=None) as batch_op:
        batch_op.drop_column('skip_cache')

    # ### end Alembic commands ###
