"""Add cloudinary fields to video processing job

Revision ID: 393b21eb335f
Revises: 4c4302aa4669
Create Date: 2026-03-05 11:29:21.226421

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '393b21eb335f'
down_revision = '4c4302aa4669'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('video_processing_job', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cloudinary_public_id', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('cloudinary_url', sa.String(length=500), nullable=True))
        batch_op.alter_column('video_path',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('video_processing_job', schema=None) as batch_op:
        batch_op.alter_column('video_path',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)
        batch_op.drop_column('cloudinary_url')
        batch_op.drop_column('cloudinary_public_id')

    # ### end Alembic commands ###
