"""Add multi-image recipe support

Revision ID: 4b8da52b6964
Revises: 4432ae39ea57
Create Date: 2025-07-25 11:25:51.444745

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b8da52b6964'
down_revision = '4432ae39ea57'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Skip creating table if it already exists
    from sqlalchemy import inspect
    inspector = inspect(op.get_bind())
    if 'multi_recipe_job' not in inspector.get_table_names():
        op.create_table('multi_recipe_job',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', name='processingstatus'), nullable=False),
        sa.Column('total_images', sa.Integer(), nullable=False),
        sa.Column('processed_images', sa.Integer(), nullable=False),
        sa.Column('recipe_id', sa.Integer(), nullable=True),
        sa.Column('combined_ocr_text', sa.Text(), nullable=True),
        sa.Column('error_message', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('completed_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['recipe_id'], ['recipe.id'], ),
        sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
    with op.batch_alter_table('processing_job', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_multi_image', sa.Boolean(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('multi_job_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('image_order', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_processing_job_multi_job_id', 'multi_recipe_job', ['multi_job_id'], ['id'])

    with op.batch_alter_table('recipe_image', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_order', sa.Integer(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('page_number', sa.Integer(), nullable=True))
        batch_op.create_index('idx_recipe_image_order', ['recipe_id', 'image_order'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe_image', schema=None) as batch_op:
        batch_op.drop_index('idx_recipe_image_order')
        batch_op.drop_column('page_number')
        batch_op.drop_column('image_order')

    with op.batch_alter_table('processing_job', schema=None) as batch_op:
        batch_op.drop_constraint('fk_processing_job_multi_job_id', type_='foreignkey')
        batch_op.drop_column('image_order')
        batch_op.drop_column('multi_job_id')
        batch_op.drop_column('is_multi_image')

    op.drop_table('multi_recipe_job')
    # ### end Alembic commands ###
