"""Add VideoProcessingJob model for video recipe import

Revision ID: 4c4302aa4669
Revises: i7j8k9l0m1n2
Create Date: 2026-02-27 15:40:06.354617

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c4302aa4669'
down_revision = 'i7j8k9l0m1n2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('video_processing_job',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('video_filename', sa.String(length=255), nullable=False),
    sa.Column('video_original_filename', sa.String(length=255), nullable=False),
    sa.Column('video_path', sa.String(length=500), nullable=False),
    sa.Column('video_size_bytes', sa.Integer(), nullable=False),
    sa.Column('video_duration_seconds', sa.Float(), nullable=True),
    sa.Column('video_content_type', sa.String(length=100), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'UPLOADING', 'EXTRACTING_AUDIO', 'TRANSCRIBING', 'EXTRACTING_FRAMES', 'ANALYZING_FRAMES', 'PARSING_RECIPE', 'COMPLETED', 'FAILED', name='videoprocessingstatus'), nullable=False),
    sa.Column('progress_message', sa.String(length=255), nullable=True),
    sa.Column('progress_percentage', sa.Integer(), nullable=False),
    sa.Column('transcript', sa.Text(), nullable=True),
    sa.Column('frame_analysis', sa.Text(), nullable=True),
    sa.Column('recipe_id', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('is_original_recipe', sa.Boolean(), nullable=False),
    sa.Column('translate_to_english', sa.Boolean(), nullable=False),
    sa.Column('cookbook_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cookbook_id'], ['cookbook.id'], ),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipe.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('video_processing_job', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_video_processing_job_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('recipe', schema=None) as batch_op:
        batch_op.alter_column('is_translated',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text("'0'"))
        batch_op.drop_index(batch_op.f('ix_recipe_course_type'))

    with op.batch_alter_table('recipe_ratings', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=False)

    with op.batch_alter_table('source', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('source', schema=None) as batch_op:
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True)

    with op.batch_alter_table('recipe_ratings', schema=None) as batch_op:
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True)

    with op.batch_alter_table('recipe', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recipe_course_type'), ['course_type'], unique=False)
        batch_op.alter_column('is_translated',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text("'0'"))

    with op.batch_alter_table('video_processing_job', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_video_processing_job_user_id'))

    op.drop_table('video_processing_job')
    # ### end Alembic commands ###
