"""Add user recipe collections table

Revision ID: a1b2c3d4e5f6
Revises: f1d2c3a4b5e6
Create Date: 2025-07-11 12:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1b2c3d4e5f6'
down_revision = 'f1d2c3a4b5e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_recipe_collections',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('recipe_id', sa.Integer(), nullable=False),
    sa.Column('added_at', sa.DateTime(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipe.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'recipe_id')
    )
    with op.batch_alter_table('user_recipe_collections', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_recipe_collections_added_at'), ['added_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_recipe_collections_recipe_id'), ['recipe_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_recipe_collections_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_recipe_collections', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_recipe_collections_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_recipe_collections_recipe_id'))
        batch_op.drop_index(batch_op.f('ix_user_recipe_collections_added_at'))

    op.drop_table('user_recipe_collections')
    # ### end Alembic commands ###