"""Add print_order_id to payments table

Revision ID: add_print_order_id
Revises: fix_missing_fields
Create Date: 2025-09-10 20:40:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'add_print_order_id'
down_revision = 'fix_missing_fields'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        # Add print_order_id column to payments table
        batch_op.add_column(sa.Column('print_order_id', sa.Integer(), nullable=True))
        
        # Add foreign key constraint for print_order_id
        batch_op.create_foreign_key('fk_payments_print_order_id', 'print_orders', ['print_order_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        # Drop foreign key constraint first
        batch_op.drop_constraint('fk_payments_print_order_id', type_='foreignkey')
        
        # Drop the added column
        batch_op.drop_column('print_order_id')
    # ### end Alembic commands ###