"""Add featured recipe fields to Recipe model

Revision ID: aeb529f3d285
Revises: 573c9d494ec2
Create Date: 2025-08-24 13:29:56.436480

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aeb529f3d285'
down_revision = '573c9d494ec2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipe', sa.Column('is_featured', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('recipe', sa.Column('featured_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recipe', 'featured_at')
    op.drop_column('recipe', 'is_featured')
    # ### end Alembic commands ###
