"""Add YouTube fields to video processing job

Revision ID: b5b229f5fefa
Revises: 4c4302aa4669
Create Date: 2026-03-06 13:22:41.140181

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5b229f5fefa'
down_revision = '4c4302aa4669'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('video_processing_job', schema=None) as batch_op:
        batch_op.add_column(sa.Column('youtube_url', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('youtube_video_id', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('extraction_method', sa.String(length=30), nullable=True))
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=17),
               type_=sa.Enum('PENDING', 'UPLOADING', 'FETCHING_METADATA', 'EXTRACTING_CAPTIONS', 'DOWNLOADING_AUDIO', 'EXTRACTING_AUDIO', 'TRANSCRIBING', 'EXTRACTING_FRAMES', 'ANALYZING_FRAMES', 'PARSING_RECIPE', 'COMPLETED', 'FAILED', name='videoprocessingstatus'),
               existing_nullable=False)
        batch_op.create_index(batch_op.f('ix_video_processing_job_youtube_video_id'), ['youtube_video_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('video_processing_job', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_video_processing_job_youtube_video_id'))
        batch_op.alter_column('status',
               existing_type=sa.Enum('PENDING', 'UPLOADING', 'FETCHING_METADATA', 'EXTRACTING_CAPTIONS', 'DOWNLOADING_AUDIO', 'EXTRACTING_AUDIO', 'TRANSCRIBING', 'EXTRACTING_FRAMES', 'ANALYZING_FRAMES', 'PARSING_RECIPE', 'COMPLETED', 'FAILED', name='videoprocessingstatus'),
               type_=sa.VARCHAR(length=17),
               existing_nullable=False)
        batch_op.drop_column('extraction_method')
        batch_op.drop_column('youtube_video_id')
        batch_op.drop_column('youtube_url')

    # ### end Alembic commands ###
