"""Add print order models for Lulu integration

Revision ID: be39cbc74574
Revises: 445834817155
Create Date: 2025-09-06 13:43:59.740995

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be39cbc74574'
down_revision = '445834817155'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('print_specifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trim_size', sa.Enum('US_LETTER', 'US_TRADE', 'DIGEST', 'SQUARE_8', 'LANDSCAPE_9x7', 'A4', 'A5', name='trimsize'), nullable=False),
    sa.Column('binding_type', sa.Enum('PERFECT_BOUND', 'COIL_BOUND', 'SADDLE_STITCH', 'CASE_WRAP', 'DUST_JACKET', name='bindingtype'), nullable=False),
    sa.Column('paper_type', sa.Enum('STANDARD_WHITE', 'STANDARD_CREAM', 'PREMIUM_WHITE', 'PREMIUM_COLOR', name='papertype'), nullable=False),
    sa.Column('cover_finish', sa.Enum('MATTE', 'GLOSS', name='coverfinish'), nullable=False),
    sa.Column('page_count', sa.Integer(), nullable=False),
    sa.Column('color_pages', sa.Boolean(), nullable=False),
    sa.Column('lulu_pod_package_id', sa.String(length=100), nullable=True),
    sa.Column('lulu_page_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('print_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('cookbook_id', sa.Integer(), nullable=False),
    sa.Column('specification_id', sa.Integer(), nullable=False),
    sa.Column('order_number', sa.String(length=100), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'PENDING_PAYMENT', 'PROCESSING', 'VALIDATING', 'PRINTING', 'SHIPPED', 'DELIVERED', 'CANCELLED', 'FAILED', 'REFUNDED', name='printorderstatus'), nullable=False),
    sa.Column('lulu_print_job_id', sa.String(length=255), nullable=True),
    sa.Column('lulu_line_item_id', sa.String(length=255), nullable=True),
    sa.Column('lulu_status', sa.String(length=100), nullable=True),
    sa.Column('interior_file_url', sa.Text(), nullable=True),
    sa.Column('cover_file_url', sa.Text(), nullable=True),
    sa.Column('interior_validation_status', sa.String(length=50), nullable=True),
    sa.Column('interior_validation_errors', sa.Text(), nullable=True),
    sa.Column('cover_validation_status', sa.String(length=50), nullable=True),
    sa.Column('cover_validation_errors', sa.Text(), nullable=True),
    sa.Column('shipping_name', sa.String(length=200), nullable=False),
    sa.Column('shipping_address_line1', sa.String(length=255), nullable=False),
    sa.Column('shipping_address_line2', sa.String(length=255), nullable=True),
    sa.Column('shipping_city', sa.String(length=100), nullable=False),
    sa.Column('shipping_state_code', sa.String(length=50), nullable=False),
    sa.Column('shipping_postal_code', sa.String(length=20), nullable=False),
    sa.Column('shipping_country_code', sa.String(length=2), nullable=False),
    sa.Column('shipping_phone', sa.String(length=50), nullable=True),
    sa.Column('shipping_email', sa.String(length=255), nullable=False),
    sa.Column('shipping_carrier', sa.String(length=100), nullable=True),
    sa.Column('tracking_number', sa.String(length=255), nullable=True),
    sa.Column('tracking_url', sa.Text(), nullable=True),
    sa.Column('estimated_delivery_date', sa.DateTime(), nullable=True),
    sa.Column('actual_delivery_date', sa.DateTime(), nullable=True),
    sa.Column('printing_cost', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('shipping_cost', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('tax_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('platform_fee', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_cost', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('stripe_payment_intent_id', sa.String(length=255), nullable=True),
    sa.Column('payment_status', sa.String(length=50), nullable=True),
    sa.Column('order_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('shipped_at', sa.DateTime(), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cookbook_id'], ['cookbook.id'], ),
    sa.ForeignKeyConstraint(['specification_id'], ['print_specifications.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lulu_print_job_id'),
    sa.UniqueConstraint('order_number')
    )
    op.create_table('print_order_status_updates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('print_order_id', sa.Integer(), nullable=False),
    sa.Column('previous_status', sa.Enum('DRAFT', 'PENDING_PAYMENT', 'PROCESSING', 'VALIDATING', 'PRINTING', 'SHIPPED', 'DELIVERED', 'CANCELLED', 'FAILED', 'REFUNDED', name='printorderstatus'), nullable=True),
    sa.Column('new_status', sa.Enum('DRAFT', 'PENDING_PAYMENT', 'PROCESSING', 'VALIDATING', 'PRINTING', 'SHIPPED', 'DELIVERED', 'CANCELLED', 'FAILED', 'REFUNDED', name='printorderstatus'), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('lulu_event_type', sa.String(length=100), nullable=True),
    sa.Column('lulu_event_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['print_order_id'], ['print_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # Skip the stripe_customer_id constraint as it already exists
    # with op.batch_alter_table('user', schema=None) as batch_op:
    #     batch_op.create_unique_constraint('uq_user_stripe_customer_id', ['stripe_customer_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Skip the stripe_customer_id constraint as it already exists
    # with op.batch_alter_table('user', schema=None) as batch_op:
    #     batch_op.drop_constraint('uq_user_stripe_customer_id', type_='unique')

    op.drop_table('print_order_status_updates')
    op.drop_table('print_orders')
    op.drop_table('print_specifications')
    # ### end Alembic commands ###
