"""Add recipe privacy fields

Revision ID: f1d2c3a4b5e6
Revises: e36f374a57b5
Create Date: 2025-07-10 12:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1d2c3a4b5e6'
down_revision = 'e36f374a57b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_public', sa.Boolean(), nullable=False, default=False))
        batch_op.add_column(sa.Column('published_at', sa.DateTime(), nullable=True))
    
    # Set default value for existing recipes (all private)
    op.execute("UPDATE recipe SET is_public = 0 WHERE is_public IS NULL")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe', schema=None) as batch_op:
        batch_op.drop_column('published_at')
        batch_op.drop_column('is_public')
    # ### end Alembic commands ###