"""add_google_books_id_to_cookbook

Revision ID: f43930b98012
Revises: 6375224c526d
Create Date: 2025-11-26 14:19:40.036209

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "f43930b98012"
down_revision = "6375224c526d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("cookbook", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("google_books_id", sa.String(length=50), nullable=True)
        )
        batch_op.create_index(
            batch_op.f("ix_cookbook_google_books_id"), ["google_books_id"], unique=True
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("cookbook", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_cookbook_google_books_id"))
        batch_op.drop_column("google_books_id")

    # ### end Alembic commands ###
