"""Add missing fields to print_orders table

Revision ID: fix_missing_fields
Revises: be39cbc74574
Create Date: 2025-09-10 12:37:00.000000

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "fix_missing_fields"
down_revision = "be39cbc74574"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("print_orders", schema=None) as batch_op:
        # Add missing columns that are in the model but not in the database
        batch_op.add_column(sa.Column("payment_id", sa.Integer(), nullable=True))
        batch_op.add_column(
            sa.Column("refund_amount", sa.Numeric(precision=10, scale=2), nullable=True)
        )
        batch_op.add_column(
            sa.Column("refund_reason", sa.String(length=500), nullable=True)
        )
        batch_op.add_column(
            sa.Column("stripe_refund_id", sa.String(length=255), nullable=True)
        )
        batch_op.add_column(sa.Column("refunded_at", sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column("paid_at", sa.DateTime(), nullable=True))

        # Add foreign key constraint for payment_id
        batch_op.create_foreign_key(
            "fk_print_orders_payment_id", "payments", ["payment_id"], ["id"]
        )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("print_orders", schema=None) as batch_op:
        # Drop foreign key constraint first
        batch_op.drop_constraint("fk_print_orders_payment_id", type_="foreignkey")

        # Drop the added columns
        batch_op.drop_column("paid_at")
        batch_op.drop_column("refunded_at")
        batch_op.drop_column("stripe_refund_id")
        batch_op.drop_column("refund_reason")
        batch_op.drop_column("refund_amount")
        batch_op.drop_column("payment_id")
    # ### end Alembic commands ###
