"""Update PaymentType enum to include PRINT_ORDER

Revision ID: update_payment_type_enum
Revises: add_print_order_id
Create Date: 2025-09-11 00:45:00.000000

"""

from alembic import op


# revision identifiers, used by Alembic.
revision = "update_payment_type_enum"
down_revision = "add_print_order_id"
branch_labels = None
depends_on = None


def upgrade():
    # PostgreSQL needs an explicit ALTER TYPE to extend the enum.
    # SQLite stores enums as plain strings, so the new value is accepted
    # implicitly — this migration is a no-op there.
    bind = op.get_bind()
    if bind.dialect.name == "postgresql":
        op.execute("ALTER TYPE paymenttype ADD VALUE IF NOT EXISTS 'PRINT_ORDER'")


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Note: PostgreSQL doesn't support removing values from enums easily
    # This would require recreating the enum and all dependent columns
    # For safety, we'll leave this as a no-op
    pass
    # ### end Alembic commands ###
